name: Refresh API list
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4 in the morning
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.6.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Refresh list
        run: pnpm crawl
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BUCKET: ${{ secrets.BUCKET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}

          