name: Refresh all sources
on:
  schedule:
    - cron: "0 4 * * *" # every day at 4 in the morning
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Set up Playwright
        run: pnpm exec playwright install
      - name: Refresh list
        run: pnpm crawl
      - name: Raise a PR if files have changed
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            data/*

          